### ISSUE TITLE
FB_AUTH in helpers.py

### ISSUE THREAD

**Issue by darkenedcolossal** [jeffmli/TinderAutomation#5]
what do i put there? a url seems to be needed. where do i find that info?

**Comment by evanrich** [comment]
how about putting your solution in here? since others (myself) are having the same problem @darkenedcolossal 

thanks!

**Comment by darkenedcolossal** [comment]
i ended up analyzing traffic in my browsers dev console while I facebook-login into tinder: I found the 2 important requests and copied them as cURL. I chained them together in a script that outputs the x-auth-token. then in `bot.py` I use the x-auth-token to start the `pynder`-session with x-auth-token.

Unfortunately I can not give my whole script, because I am not sure what sensible data might be hidden in all those http-parameters...

But here more details on the requests you are looking for:
1. The response on the request to https://www.facebook.com/v2.8/dialog/oauth contains an `access_token` that can be used in
2. the request to https://api.gotinder.com/v2/auth/login/facebook. The response will contain the x-auth-token.

Unfortunately it seems that my request "1." contains some data, that was already present but changes from time to time: the value for `xs` in the cookie header. I have to replace it from time to time. I just go to the browser session, look at the cookies and copy the xs value.

sorry, for the bad knowledge management. maybe you can do it better. :)
maybe you can even fix the original `helper.py`... ;)
